# Generated by Django 4.1.4 on 2023-02-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spots',
            name='rating',
        ),
        migrations.AddField(
            model_name='spots',
            name='known',
            field=models.CharField(default='', max_length=500),
        ),
    ]
