# Generated by Django 4.1.4 on 2023-02-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0002_remove_spots_rating_spots_known'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spots',
            name='known',
            field=models.TextField(default='', max_length=500),
        ),
    ]
